version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scientist
      POSTGRES_PASSWORD: laboratory
      POSTGRES_DB: ntv
    ports:
      - "6010:5432"