version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scientist
      POSTGRES_PASSWORD: laboratory
      POSTGRES_DB: ntv
    ports:
      - "6010:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      #- ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: