server:
  port: 21413
  servlet:
    context-path: /
    session:
      timeout: 600s

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/studs
    username: s312693
    password: ***
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings